name: nest-demo
services:
  nest:
    image: nest-demo:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_demo
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
