name: Build App

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

        id: build
      - name: Build
        run: pnpm run build

      - uses: LouisBrunner/checks-action@v2.0.0
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test Build
          conclusion: ${{ job.status }}
          output: |
            {"summary":"${{ steps.build.outputs.summary }}"}
